Test system improved

diff --git a/src/base/Makefile b/src/base/Makefile
--- a/src/base/Makefile
+++ b/src/base/Makefile
@@ -70,15 +70,19 @@ TEST_TARGETS				= $(call get_targets,$(TEST_SOURCES_CPP))
 TEST_TARGET_FILES			= $(call get_test_files,$(TEST_TARGETS))
 
 
-.PHONY: all clean check dirs main run-tests
+.PHONY: all clean clean-tests check dirs main tests run-tests
 .SILENT:
 
 
 all: dirs main
 
 
-clean:
-	rm -rf $(OBJECT_FILES) $(TEST_TARGET_FILES) $(TARGET_LIB_FILE)
+clean: clean-tests
+	rm -rf $(OBJECT_FILES) $(TARGET_LIB_FILE)
+
+
+clean-tests:
+	rm -rf $(TEST_OBJECT_FILES) $(TEST_TARGET_FILES)
 
 
 # Tests targets
@@ -93,16 +97,19 @@ dirs:
 main: $(TARGET_LIB_FILE)
 
 
-run-tests: $(TEST_TARGET_FILES)
-	for T in $(TEST_TARGETS); do															\
-		echo "$(COLOR_RUN)Running test: $$T...$(COLOR_RESET)";								\
-		$(call get_test_files,$$T);															\
-		STATUS=$$?;																			\
-		if [ "X$$STATUS" == 'X0' ]; then													\
-			echo "$(COLOR_PASS)Test $$T passed.$(COLOR_RESET)";								\
-		else																				\
-			echo "$(COLOR_FAIL)Test $$T failed with code: $$STATUS.$(COLOR_RESET)";			\
-		fi;																					\
+tests: $(TEST_TARGET_FILES)
+
+
+run-tests: tests
+	for T in $(TEST_TARGETS); do																		\
+		echo "$(COLOR_RUN)Running test: $$T ($(MODULE_NAME))...$(COLOR_RESET)";							\
+		$(call get_test_files,$$T);																		\
+		STATUS=$$?;																						\
+		if [ "X$$STATUS" == 'X0' ]; then																\
+			echo "$(COLOR_PASS)Test $$T ($(MODULE_NAME)) passed.$(COLOR_RESET)";						\
+		else																							\
+			echo "$(COLOR_FAIL)Test $$T ($(MODULE_NAME)) failed with code: $$STATUS.$(COLOR_RESET)";	\
+		fi;																								\
 	done
 
 
@@ -118,6 +125,6 @@ $(TARGET_LIB_FILE): $(HEADER_FILES) $(OBJECT_FILES)
 
 
 # Tests
-$(TEST_DIR_CURR)/%: $(OBJECTS_DIR)/%.o $(HEADER_FILES) $(OBJECT_FILES)
+$(TEST_DIR_CURR)/%: $(OBJECTS_DIR_CURR)/%.o $(HEADER_FILES) $(OBJECT_FILES)
 	@echo "    $(COLOR_RUN)Linking test: $(subst $(TEST_DIR_CURR)/,,$@) ($(MODULE_NAME))...$(COLOR_RESET)"
 	$(call gpp_link) -o '$@' '$<' $(OBJECT_FILES)
